name: Release
on:
  workflow_dispatch:
    inputs:
      desc:
        description: 'Description'
        required: false
        default: 'Manual release'

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      HUSKY: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup.yaml

      - name: Build package
        run: yarn build

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Add Dependencies
        run: yarn add --immutable release-it @release-it/conventional-changelog

      - name: Release
        run: yarn release-it --ci
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
