name: Test
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Unit
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft && github.actor != 'dependabot[bot]' }}
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup.yaml

      - name: Run tests
        run: yarn jest --runInBand
